---
language: python
services: docker

env:
  global:
    - ROLE_NAME: add_repo
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: centos8
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: debian10

install:
  - pip install molecule docker

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
